### ISSUE TITLE
City Planning Commission

### ISSUE THREAD

**Issue by skorasaurus** [City-Bureau/city-scrapers-cle#12]
verify if it works; they did a redesign; 

the new url to scrape from is: https://planning.clevelandohio.gov/designreview/schedule.php
(this is correct, despite the URL; this also has the planning committee there

**Comment by zabrahams** [comment]
Since this was is pretty similar to the design review (#15) - I can probably get it done pretty quickly!

**Comment by skorasaurus** [comment]
done in https://github.com/City-Bureau/city-scrapers-cle/pull/37 :)
