### ISSUE TITLE
Landmarks Commision

### ISSUE THREAD

**Issue by skorasaurus** [City-Bureau/city-scrapers-cle#14]
At https://cleveland.documenters.org/scrapers/ ; it's reported the landmarks committee doesn't have any upcoming meetings 

![testing](https://user-images.githubusercontent.com/955351/102413181-8acf9f80-3fc2-11eb-9dc2-57d211199ee1.png)

 
But at https://cleveland.documenters.org/agencies/cleveland-landmarks-commission-158/ upcoming meetings are listed.
 
and then if you go to the individual meeting's page within documenters, (e.g. 
https://cleveland.documenters.org/meetings/landmarks-commission-32679/) it says the meeting is canceled.  !??!? 

This appears to be the old page that was scraped: http://city.cleveland.oh.us/CityofCleveland/Home/Government/CityAgencies/CityPlanningCommission/LandmarksCommission

This is the new page: https://planning.clevelandohio.gov/landmark/AGENDALIST.html

**Comment by zabrahams** [comment]
@skorasaurus Hi! Is it cool if I take a stab at this one over the next few days?

**Comment by zabrahams** [comment]
It looks like the site has changed again! The new site seems to be at:

https://planning.clevelandohio.gov/landmark/agenda.php

**Comment by skorasaurus** [comment]
@zabrahams yep, go for it; I'll check out the PR over the weekend.

**Comment by skorasaurus** [comment]
worked on https://github.com/City-Bureau/city-scrapers-cle/pull/31 ; I'll leave this open just to make sure that it's being pulled properly at in a couple days https://cleveland.documenters.org/scrapers/

**Comment by skorasaurus** [comment]
Thank again @zabrahams !!! 

the github cron job for resumed for all scrapers resumed after I reverted the lxml results https://github.com/City-Bureau/city-scrapers-cle/pull/33 

Now, the landmarks commission scraper is working with your fixes; 
see the results at https://cleveland.documenters.org/agencies/cleveland-landmarks-commission-158/  =)
