### ISSUE TITLE
Write Scraper for Cuyahoga County Citizens' Advisory Council on Equity (CACE) (higher priority)

### ISSUE THREAD

**Issue by skorasaurus** [City-Bureau/city-scrapers-cle#19]
This would be a new scraper; for: 
Cuyahoga County Citizens' Advisory Council on Equity (CACE)

This does a have a corresponding page at the Documenters already made for it: 
https://cleveland.documenters.org/agencies/cuyahoga-county-citizens-advisory-council-on-equity-cace-250/

The meeting information is at: http://bc.cuyahogacounty.us/en-US/Citizens-Advisory-Council-Equity.aspx?Year=2021

**Comment by pjsier** [comment]
@skorasaurus just checking, are these issues you want to make available to Open Cleveland folks or items you want me to take care of?

**Comment by skorasaurus** [comment]
If you're able to take of this one, that would be great; there's plenty of other issues that open cleveland folks can help with :)

**Comment by pjsier** [comment]
@skorasaurus sure! Feel free to tag me on any issues that would be helpful for me to do

**Comment by pjsier** [comment]
Closed by 55ba094
