### ISSUE TITLE
Fix Board of Elections - Updated Website with new Calendar Page

### ISSUE THREAD

**Issue by PaulR-Docs** [City-Bureau/city-scrapers-cle#39]
There is a new Board of Elections Website with a new calendar page, so we will need to change the scraper to reflect the current page here: https://boe.cuyahogacounty.gov/calendar 

This is the old scraper: https://github.com/City-Bureau/city-scrapers-cle/blob/main/city_scrapers/spiders/cuya_elections.py

**Comment by alfenn** [comment]
I'd like to claim this issue!

**Comment by PaulR-Docs** [comment]
Hi @alfenn. Feel free to go for it. @skorasaurus can assign the issue to you as the admin. The new page for this site is quite different from the old one which the current scraper is built for, so a lot may need to change in the way the scraper is written.

**Comment by skorasaurus** [comment]
Fixed thanks to @alfenn =)
