### ISSUE TITLE
Mental Health Response Advisory Committee Scraper Creation 

### ISSUE THREAD

**Issue by PaulR-Docs** [City-Bureau/city-scrapers-cle#45]
The URL for the MHRAC committee calendar is here: [https://www.adamhscc.org/about-us/current-initiatives/task-forces-and-coalitions/mental-health-response-advisory-committee-mhrac](https://github.com/City-Bureau/city-scrapers-cle/issues/url) 

Needs to be created from scratch. All the General MHRAC meetings and subcommittee meetings are on this calendar.

Agency is ADAMHS Board of Cuyahoga County.

**Comment by alfenn** [comment]
I'd like to claim this one!

**Comment by PaulR-Docs** [comment]
@alfenn I have started on this, but am pretty behind on it, so you can definitely go for it and let me know if you get stuck or want any help!
