### ISSUE TITLE
cle_design_review fix

### ISSUE THREAD

**Issue by haileyhoyat** [City-Bureau/city-scrapers-cle#52]
@skorasaurus 

hey. Paul mentioned this scraper broke yesterday (08/22/2022). i think i fixed it, making a PR now. 

bug: lines#83-85 .split() the text for each select item, and assumes the return of two items max. however, some options have additional verbiage on their item so returns more than two items. 

fix: lines#83-88 (on PR#53) now extract the month and day separately instead of assuming the return of two items. 

<img width="927" alt="Screen Shot 2022-08-23 at 9 32 28 AM" src="https://user-images.githubusercontent.com/25486536/186172188-0920e6b3-ac6e-40f7-825a-18176e050465.png">

**Comment by skorasaurus** [comment]
Sounds good to me; thanks for the context and including a screenshot.
